language: ruby
rvm:
 - "2.2.2"
services:
 - redis-server
before_script:
  - cp config/database.yml.travis config/database.yml
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec
